// Code generated by agent-service/scripts/generate-contract-artifacts.ts. Do not edit.

package graph

var generatedGraphCommandOpNames = []string{
	"create_node",
	"update_node_config",
	"rename_node",
	"delete_node",
	"connect_nodes",
	"disconnect_edge",
	"move_nodes",
	"create_group",
	"move_nodes_to_group",
	"rename_group",
	"dissolve_group",
	"reorder_edges",
}
