import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { GRAPH_COMMAND_OPS } from "../src/graph-command-schema.js";
import { TOOL_MANIFEST, TOOL_MANIFEST_VERSION } from "../src/tool-manifest.js";

const scriptDir = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(scriptDir, "../..");

const uniqueToolKinds = [...new Set(TOOL_MANIFEST.map((entry) => entry.ui_kind))];
const runtimePolicy = (await readFile(resolve(repoRoot, "go/prompts/agent/runtime-policy.md"), "utf8")).trim();

const webArtifact = `// Code generated by agent-service/scripts/generate-contract-artifacts.ts. Do not edit.\n\nexport const TOOL_MANIFEST_VERSION = ${JSON.stringify(TOOL_MANIFEST_VERSION)} as const;\nexport const AGENT_TOOL_STEP_KINDS = ${JSON.stringify(uniqueToolKinds)} as const;\nexport type AgentToolStepKindFromManifest = (typeof AGENT_TOOL_STEP_KINDS)[number];\n`;

const agentArtifact = `// Code generated by agent-service/scripts/generate-contract-artifacts.ts. Do not edit.\n\npackage agent\n\nconst ToolManifestVersion = ${JSON.stringify(TOOL_MANIFEST_VERSION)}\n`;

const graphArtifact = `// Code generated by agent-service/scripts/generate-contract-artifacts.ts. Do not edit.\n\npackage graph\n\nvar generatedGraphCommandOpNames = []string{\n${GRAPH_COMMAND_OPS.map((name) => `\t${JSON.stringify(name)},`).join("\n")}\n}\n`;
const runtimePolicyArtifact = `// Code generated by agent-service/scripts/generate-contract-artifacts.ts. Do not edit.\n\nexport const RUNTIME_POLICY = ${JSON.stringify(runtimePolicy)};\n`;

async function writeArtifact(path: string, content: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, content, "utf8");
}

await Promise.all([
  writeArtifact(
    resolve(repoRoot, "web/src/pages/workbench/agent/toolManifest.generated.ts"),
    webArtifact,
  ),
  writeArtifact(resolve(repoRoot, "go/internal/agent/tool_manifest_generated.go"), agentArtifact),
  writeArtifact(resolve(repoRoot, "go/internal/graph/graph_command_schema_generated.go"), graphArtifact),
  writeArtifact(resolve(repoRoot, "agent-service/src/runtime-policy.generated.ts"), runtimePolicyArtifact),
]);
