#!/usr/bin/env bash
# Assemble a versioned install package: locked compose, env sample, VERSION,
# images.env, install + backup/restore instructions and scripts.
# Optionally docker-save product images for offline / local-registry-free hosts.
#
# Usage:
#   bash scripts/release-pack.sh
#   RELEASE_PACK_SAVE_IMAGES=1 bash scripts/release-pack.sh
#   RELEASE_PACK_OUT=/tmp/pf-pack bash scripts/release-pack.sh
#
# Does not mutate shared Compose projects. Does not claim D3/R6.

set -euo pipefail

script_dir="$(cd "$(dirname "$0")" && pwd)"
# shellcheck source=release_common.sh
source "${script_dir}/release_common.sh"

root="$(release_repo_root)"
cd "$root"
release_resolve_meta "$root"

out_root="${RELEASE_PACK_OUT:-${root}/dist/release}"
pkg_name="productflow-${PRODUCTFLOW_IMAGE_TAG}"
pkg_dir="${out_root}/${pkg_name}"
save_images="${RELEASE_PACK_SAVE_IMAGES:-0}"

echo "[release-pack] repo_root=$root"
echo "[release-pack] package_dir=$pkg_dir"
release_print_meta | sed 's/^/[release-pack] /'

rm -rf "$pkg_dir"
mkdir -p "$pkg_dir"

cp "${root}/release/docker-compose.yml" "${pkg_dir}/docker-compose.yml"
cp "${root}/release/docker-compose.prod-ports.yml" "${pkg_dir}/docker-compose.prod-ports.yml"
cp "${root}/release/.env.example" "${pkg_dir}/.env.example"
cp "${root}/release/README.md" "${pkg_dir}/README.md"

mkdir -p "${pkg_dir}/scripts"
cp "${root}/scripts/release_common.sh" "${pkg_dir}/scripts/release_common.sh"
cp "${root}/scripts/release_backup_common.sh" "${pkg_dir}/scripts/release_backup_common.sh"
cp "${root}/scripts/release-backup.sh" "${pkg_dir}/scripts/release-backup.sh"
cp "${root}/scripts/release-restore.sh" "${pkg_dir}/scripts/release-restore.sh"
chmod +x \
  "${pkg_dir}/scripts/release-backup.sh" \
  "${pkg_dir}/scripts/release-restore.sh"

release_write_version_file "${pkg_dir}/VERSION"

# images.env is the pin consumed by compose variable substitution.
grep -E '^(PRODUCTFLOW_(GO|AGENT|WEB|POSTGRES|REDIS)_IMAGE)=' "${pkg_dir}/VERSION" >"${pkg_dir}/images.env"

cat >"${pkg_dir}/SHA256SUMS" <<EOF
# Generated by scripts/release-pack.sh for ${pkg_name}
EOF
(
  cd "$pkg_dir"
  sha256sum \
    docker-compose.yml \
    docker-compose.prod-ports.yml \
    .env.example \
    README.md \
    VERSION \
    images.env \
    scripts/release_common.sh \
    scripts/release_backup_common.sh \
    scripts/release-backup.sh \
    scripts/release-restore.sh \
    >>SHA256SUMS
)

if [[ "$save_images" == "1" ]]; then
  mkdir -p "${pkg_dir}/images"
  archive="${pkg_dir}/images/productflow-images-${PRODUCTFLOW_IMAGE_TAG}.tar"
  echo "[release-pack] docker save -> $archive"
  docker image inspect "$PRODUCTFLOW_GO_IMAGE" "$PRODUCTFLOW_AGENT_IMAGE" "$PRODUCTFLOW_WEB_IMAGE" >/dev/null
  docker save -o "$archive" \
    "$PRODUCTFLOW_GO_IMAGE" \
    "$PRODUCTFLOW_AGENT_IMAGE" \
    "$PRODUCTFLOW_WEB_IMAGE" \
    "$PRODUCTFLOW_POSTGRES_IMAGE" \
    "$PRODUCTFLOW_REDIS_IMAGE"
  (
    cd "$pkg_dir"
    sha256sum "images/productflow-images-${PRODUCTFLOW_IMAGE_TAG}.tar" >>SHA256SUMS
  )
fi

tarball="${out_root}/${pkg_name}.tar.gz"
mkdir -p "$out_root"
tar -C "$out_root" -czf "$tarball" "$pkg_name"
(
  cd "$out_root"
  sha256sum "${pkg_name}.tar.gz" >"${pkg_name}.tar.gz.sha256"
)

echo "[release-pack] wrote $pkg_dir"
echo "[release-pack] wrote $tarball"
echo "[release-pack] note: package pins image *names/tags*; digest locking requires a successful build+push or docker save of those tags"
